name: CI Cypress

on:
  push:
  pull_request:
    branches: [main]

jobs:
  e2e:
    # if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: npm
      - run: npm ci
      - name: E2E tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: video-e2e
          path: cypress/videos
